Project/Pages/Admin/AddRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using GoogleAuth;
using Microsoft.AspNetCore.Mvc.Rendering;
using Google.Apis.Calendar.v3.Data;

namespace Project.Pages.Admin
{
    public class AddRoom : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string Name { get; set;}
        [BindProperty(SupportsGet = true)]
        public string Description { get; set;}

        public string Notifications { get; set;}

        public async Task<IActionResult> OnPostAsync()
        {

            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            foreach (CalendarListEntry calendar in calendarList.Items)
            {
                if (calendar.Summary == Name)
                {
                    TempData["Notifications"] = "Error: Room with the same name alredy exists";
                    TempData.Peek("Notifications");
                    Notifications = (String)TempData["Notifications"];
                    Console.WriteLine(TempData["Notifications"]);
                    Console.WriteLine("Room :" + Notifications);
                    return Page();
                }
            }

            Calendar newRoom = new Calendar();
            newRoom.Summary = Name;
            newRoom.Description = Description;
            service.Calendars.Insert(newRoom).Execute();
            TempData["Notifications"] = "Room has been created successfully";
            TempData.Peek("Notifications");
            Notifications = (String)TempData["Notifications"];
            return Page();
        } 
       
    }
}

Project/Pages/Admin/Booking.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using GoogleAuth;
using Microsoft.AspNetCore.Mvc.Rendering;
using Google.Apis.Calendar.v3.Data;

namespace Project.Pages.Admin
{
    public class Booking : PageModel
    {
        public SelectList? Rooms { get; set;}
        [BindProperty(SupportsGet = true)]
        public string Title { get; set;}
        [BindProperty(SupportsGet = true)]
        public string RoomId { get; set;}
        [BindProperty(SupportsGet = true)]
        public DateTime StartDate { get; set;}
        [BindProperty(SupportsGet = true)]
        public DateTime EndDate { get; set;}
        [BindProperty(SupportsGet = true)]
        public string Atendee { get; set;}
        [BindProperty(SupportsGet = true)]
        public string Description { get; set; }
        private string Id { get; set; }

        public async Task OnGetAsync()
        {
            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            IEnumerable<CalendarListEntry> roomList = calendarList.Items.Where(c => c.Description != null);
            roomList = roomList.Where(c => c.Description.Contains("Ruang"));
            IEnumerable<string> room = roomList.Select(c => c.Summary);

            Rooms = new SelectList(room);

        }
        public async Task<IActionResult> OnPostAsync()
        {

            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            foreach (CalendarListEntry calendar in calendarList.Items)
            {
                if (calendar.Summary == RoomId)
                {
                    Id = calendar.Id;
                    break;
                }
            }


            Event newEvent = new Event
            {
                Summary = Title,
                Start = new EventDateTime
                {
                    DateTime = DateTime.Parse(StartDate.ToString("yyyy-MM-dd HH:mm")),
                    TimeZone = "GMT+7"
                },
                End = new EventDateTime
                {
                    DateTime = DateTime.Parse(EndDate.ToString("yyyy-MM-dd HH:mm")),
                    TimeZone = "GMT+7"
                },
                Attendees = new List<EventAttendee>()
                {
                    new EventAttendee()
                    {
                        Email = Atendee,
                    }
                },
                Description = Description,
                Location = "Jakarta"
            };
            service.Events.Insert(newEvent, Id).Execute();

            return RedirectToPage("/Admin/Index");
        } 
    }
}

Project/Pages/Admin/DeleteEvent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using GoogleAuth;
using Microsoft.AspNetCore.Mvc.Rendering;
using Google.Apis.Calendar.v3.Data;

namespace Project.Pages.Admin
{
    public class DeleteEvent : PageModel
    {
        public Events events = new Events();
        public string eventName { get; set; }
        public string eventId { get; set; }
        public string calId;
        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id ==null)
            {
                return NotFound();
            }
            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            //alendarListEntry  roomToModify = null;
            foreach (CalendarListEntry room in calendarList.Items)
            {
                foreach (var e in service.Events.List(room.Id).Execute().Items)
                {
                    if (e.Id == id)
                    {
                        eventId = e.Id;
                        eventName = e.Summary;
                        calId = room.Id;

                    }
                    break;
                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(string? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            //alendarListEntry  roomToModify = null;
            foreach (CalendarListEntry room in calendarList.Items)
            {
                foreach (var e in service.Events.List(room.Id).Execute().Items)
                {
                    if (e.Id == id)
                    {
                        eventId = e.Id;
                        eventName = e.Summary;
                        calId = room.Id;

                    }
                    break;
                }
            }
            service.Events.Delete(calId,eventId).Execute();
            return RedirectToPage("/Admin/SelectRoom");
        }
    }
}

Project/Pages/Admin/DeleteRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using GoogleAuth;
using Microsoft.AspNetCore.Mvc.Rendering;
using Google.Apis.Calendar.v3.Data;

namespace Project.Pages.Admin
{
    public class DeleteRoom : PageModel
    {
        public CalendarListEntry? Rooms { get; set;}
        public string? RoomId {get; set;}
        public string Id {get; set;}
        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id ==null)
            {
                return NotFound();
            }
            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            //alendarListEntry  roomToModify = null;
            foreach (CalendarListEntry room in calendarList.Items)
            {
                if (room.Id== id)
                {
                    Rooms = room;
                    break;
                }
            }

            if (Rooms == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(string? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            //alendarListEntry  roomToModify = null;
            foreach (CalendarListEntry room in calendarList.Items)
            {
                if (room.Id == id)
                {
                    Rooms = room;
                    break;
                }
            }

            if (Rooms == null)
            {
                return NotFound();
            }
            service.Calendars.Delete(Rooms.Id).Execute();
            return RedirectToPage("/Admin/SelectRoom");
        }
    }
}

Project/Pages/Admin/DetailRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using GoogleAuth;
using Microsoft.AspNetCore.Mvc.Rendering;
using Google.Apis.Calendar.v3.Data;

namespace Project.Pages.Admin
{
    public class DetailRoom : PageModel
    {
        public Events events = new Events();
        public CalendarListEntry? Rooms { get; set;}
         public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id ==null)
            {
                return NotFound();
            }
            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            //alendarListEntry  roomToModify = null;
            foreach (CalendarListEntry room in calendarList.Items)
            {
                if (room.Id== id)
                {
                    Rooms = room;
                    events  = service.Events.List(room.Id).Execute();
                    break;
                }
            }

            if (events == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Project/Pages/Admin/EditRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using GoogleAuth;
using Microsoft.AspNetCore.Mvc.Rendering;
using Google.Apis.Calendar.v3.Data;

namespace Project.Pages.Admin
{
    public class EditRoom : PageModel
    {
        public Calendar Rooms = new Calendar();
        public string? RoomId {get; set;}
        public string Id {get; set;}
        [BindProperty]
        public string? Name {get; set;}
        [BindProperty]
        public string? Description {get; set;}
        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id ==null)
            {
                return NotFound(); 
            }
            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            //alendarListEntry  roomToModify = null;
            foreach (CalendarListEntry room in calendarList.Items)
            {
                if (room.Id== id)
                {
                    Name = room.Summary;
                    Description = room.Description;
                    Id = room.Id;
                    break;
                }
            }

            return Page();
        }
        public async Task<IActionResult> OnPostAsync(string? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            //alendarListEntry  roomToModify = null;
            foreach (CalendarListEntry room in calendarList.Items)
            {
                if (room.Id == id)
                {
                    Id = room.Id;
                    Rooms.ETag = room.ETag;
                    Rooms.Kind = room.Kind;
                    break;
                }
            }

            if (Id == null)
            {
                return NotFound();
            }
            
            Rooms.Id = Id;
            Rooms.Summary = Name;
            Rooms.Description = Description;
            Console.WriteLine("summary = " + Name +" ||"+ Rooms.Summary );
            Console.WriteLine("description = " + Description + "||" + Rooms.Description );
            service.Calendars.Update(Rooms, Id).Execute();
            return RedirectToPage("/Admin/SelectRoom");
        }
    }
}

Project/Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using GoogleAuth;
using Google.Apis.Calendar.v3.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Project.Pages.Admin
{
    public class Index : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set;}
        public SelectList? Rooms { get; set;}
        [BindProperty(SupportsGet = true)]
        public string? Room { get; set;}
        public string ListCalendar = "&src=id.indonesian%23holiday%40group.v.calendar.google.com";


        public async Task OnGetAsync()
        {
            var service = GoogleCredential.CreateCredential();
            CalendarList calendarList = service.CalendarList.List().Execute();
            IEnumerable<CalendarListEntry> roomList = calendarList.Items.Where(c => c.Description != null);
            roomList = roomList.Where(c => c.Description.ToLower().Contains("ruang"));

            if (!string.IsNullOrEmpty(Room))
            {
                // filter based on size
                foreach (CalendarListEntry room in roomList)
                {
                    if (room.Description.ToLower().Contains(Room.ToLower()))
                    {
                        ArrangeLink(room.Id);
                    }
                }
            }
            if(!string.IsNullOrEmpty(SearchString))
            {
                // filter 
                foreach (CalendarListEntry room in roomList)
                {
                    if (room.Description.ToLower().Contains(SearchString.ToLower()) || room.Summary.ToLower().Contains(SearchString.ToLower()))
                    {
                        ArrangeLink(room.Id);
                    }
                }
            }
            if (string.IsNullOrEmpty(Room)&&string.IsNullOrEmpty(SearchString)) {
                foreach (CalendarListEntry room in roomList)
                {
                    ArrangeLink(room.Id);
                }
            }

        }

        public void ArrangeLink(string link)
        {
            string src = "&src=";
            ListCalendar = ListCalendar + src + link;
        }
    }
    
}

Project/Pages/Admin/ListUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserData;

namespace ListUser.Pages
{
    public class IndexModel : PageModel
    {
        private readonly UserRepository _userRepository;

        public IndexModel(UserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public List<User> Users { get; set; }

        public void OnGet()
        {
            Users = _userRepository.GetAllUsers();
        }

        [BindProperty]
        public User NewUser { get; set; }
        public bool IsUserDeleted { get; set; }

        [HttpPost]
        public IActionResult OnPostCreate()
        {
            if (ModelState.IsValid)
            {
                _userRepository.CreateUser(NewUser);
                return RedirectToPage();
            }

            return Page();
        }
        [HttpPost]
        public IActionResult OnPostDelete(int userId)
        {
            if(ModelState.IsValid)
            {
            _userRepository.DeleteUser(userId);
            return RedirectToPage();

            }
            return Page();
        }

        [HttpPost]
        public IActionResult OnPostUpdateRole(User updatedUser)
        {
            var user = _userRepository.GetUser(updatedUser.UserId);
            if (user != null)
            {
                user.UserName = updatedUser.UserName;
                user.Password = updatedUser.Password;
                user.Role = updatedUser.Role;

                _userRepository.UpdateUser(user);
                return RedirectToPage();
            }

            return NotFound();
        }

    }
}

Project/Pages/Booking.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Booking.Pages;

public class BookingModel : PageModel
{
    
}

Project/Pages/Admin/Account.cshtml
@page
@{
    ViewData["Title"] = "Account";
}
@{
    Layout = "/Pages/Shared/_LayoutAdmin.cshtml";
}

<div class="container rounded bg-white mt-5">
        <div class="row">
            <div class="col-md-4 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" src="https://i.imgur.com/0eg0aG0.jpg" width="90"><span class="font-weight-bold">Teguh Riyadi</span><span class="text-black-50">TeguhRiyadi@gmail.com</span></div>
            </div>
            <div class="col-md-8">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <label>Username</label>
                            <input type="text" class="form-control" placeholder="first name" value="Teguh">
                            </div>
                        <div class="col-md-6"><label>Username</label><input type="text" class="form-control" value="" placeholder="UserName"></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6"> <label>Email</label> <input type="text" class="form-control" placeholder="Email" value="Teguh@gmail.com"></div>
                        <div class="col-md-6"><label>Password</label><input type="text" class="form-control" value="*****" placeholder="Password"></div>
                    </div>
                    <div class="mt-5 text-right"><button class="btn btn-primary profile-button" type="button">Save Profile</button></div>
                </div>
            </div>
        </div>
    </div>

Project/Pages/Admin/AddRoom.cshtml
@page
@model Project.Pages.Admin.AddRoom
@{
    Layout = "/Pages/Shared/_LayoutAdmin.cshtml";
}
@{
    ViewData["Title"] = "AddRoom";
}

<h1 class = "Title">@ViewData["Title"]</h1>

<main>
<div class="container">
    <form method="post">
        <div class="container3">

            <div class="container1">
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Title</label>
                    <input asp-for="Name" type="Text" class="form-control" id="exampleFormControlInput1" placeholder="Name for new room">
                </div>
        </div>     
        <div class="mb-3">

            <label for="exampleFormControlTextarea1" class="form-label">Description</label>
            <select asp-for="Description" class="form-select form-control" id="exampleFormControlTextarea1" rows="3">
                <option value="">--Select Room--</option>
                <option value="Ruangan Besar">Ruangan Besar(>10)</option>
                <option value="Ruangan Sedang">Ruangan Sedang (5-10) </option>
                <option value="Ruangan Kecil" >Ruangan Kecil (<5) </option>
            </select>
        </div>              
            <div class="mb-3 btn">
            <button type="submit" value="booking" class="btn-blue">Create</button>
             </div> 
    </form>    
        @if (!string.IsNullOrEmpty(Model.Notifications))
        {

            @if (Model.Notifications.Contains("Error"))
            {
                    <div class="alert alert-danger" role="alert">
                    @TempData.Peek("Notifications");
                     </div>
            }else
            {
                <div class="alert alert-success" role="alert">
                    @TempData.Peek("Notifications");
                     </div>
            }
        }

</div>
</main>

Project/Pages/Admin/Booking.cshtml
@page
@model Project.Pages.Admin.Booking
@{
    Layout = "/Pages/Shared/_LayoutAdmin.cshtml";
}
@{
    ViewData["Title"] = "Booking Meeting Room";
}

<h1 class="title">@ViewData["Title"]</h1>

<main>
<div class="container">
    <form method="post">
        <div class="container3">

            <div class="container1">
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Title</label>
                    <input asp-for="Title" type="Text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                </div>
                <div>
                    <label>Room</label>
                    <select  asp-items="Model.Rooms" class="form-select" aria-label="Default select example" asp-for="RoomId">
                        <option value="">--Select Room--</option>
                    </select>
                </div>
                  <div class="mb-3 mt-3">
            <label for="exampleFormControlTextarea1" class="form-label">Description</label>
            <textarea asp-for="Description" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
            </div>

            <div class="container2">
                 <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Start Date</label>
                <input asp-for="StartDate" type="datetime-local" class="form-control" id="exampleFormControlInput1" >
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">End Date</label>
                <input asp-for="EndDate" type="datetime-local" class="form-control" id="exampleFormControlInput1" >
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Atendee</label>
                <input asp-for="Atendee" type="Email" class="form-control" id="exampleFormControlInput1" placeholder="email">
            </div>

        </div>     
      
        <div class="mb-3 btn">
            <button type="submit" value="booking" class="btn-blue">Booking</button>
        </div>
    </form>
</div>
</main>

Project/Pages/Admin/ListUser.cshtml
@page
@model ListUser.Pages.IndexModel

@{
    Layout = "/Pages/Shared/_LayoutAdmin.cshtml";
}

@{
    ViewData["Title"] = "List Users";
}
<main>
    <h1 class="title">@ViewData["Title"]</h1>
    <div class="container">
        <div class="mb-3 btn">
            <button class="btn-blue" data-toggle="modal" data-target="#createModal">Create User</button>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        <span class="custom-checkbox">
                            <input type="checkbox" id="selectAll">
                            <label for="selectAll"></label>
                        </span>
                    </th>
                    <th scope="col">#</th>
                    <th scope="col">Email</th>
                     <th scope="col" >Password</th>
                    <th scope="col">Role</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model.Users)
                {
                    <tr scope="row">
                        <td>
                            <span class="custom-checkbox">
                                <input type="checkbox" id="checkbox1" name="options[]" value="1">
                                <label for="checkbox1"></label>
                            </span>
                        </td>
                        <td>@user.UserId</td>
                        <td>@user.UserName</td>
                         <td type="password">@user.Password</td>
                        <td>@user.Role</td>
                        <td>
                            <a href="#" class="update"
                                onclick="openUpdateModal(event,'@user.UserId', '@user.UserName', '@user.Role', '@user.Password')"
                                data-toggle="modal">
                                <i class="material-icons" data-toggle="tooltip" title="Update">&#xE254;</i>
                            </a>

                            <a href="#" class="delete" onclick="deleteUser('@user.UserId')">
                                <i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i>
                            </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>


        <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="createModalLabel">Create User</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-page-handler="Create">
                            <div class="form-group">
                                <label for="UserName">Username:</label>
                                <input type="text" class="form-control" id="UserName" name="NewUser.UserName" required>
                            </div>
                            <div class="form-group">
                                <label for="Password">Password:</label>
                                <input type="password" class="form-control" id="Password" name="NewUser.Password"
                                    required>
                            </div>
                            <div class="form-group">
                                <label for="Role">Role:</label>
                                <select class="form-control form-select" id="Role" name="NewUser.Role" required>
                                    <option value="Admin">Admin</option>
                                    <option value="User">User</option>
                                </select>
                            </div>
                            <div class="mb-3 btn">
                                <button type="submit" class="btn-blue">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateModalLabel">Update User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" asp-page-handler="UpdateRole">
                        <input type="hidden" id="updateUserId" name="userId" value="">
                        <div class="form-group">
                            <label for="updateUserName">Username:</label>
                            <input type="text" class="form-control" id="updateUserName" name="userName" required>
                        </div>
                        <div class="form-group">
                            <label for="updatePassword">Password:</label>
                            <input type="password" class="form-control" id="updatePassword" name="password" required>
                        </div>
                        <div class="form-group">
                            <label for="updateRole">Role:</label>
                            <select class="form-control form-select" id="updateRole" name="role" required>
                                <option value="Admin">Admin</option>
                                <option value="User">User</option>
                            </select>
                        </div>
                        <div class="mb-3 btn">
                            <button type="submit" class="btn-blue">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</main>
<script>
    function deleteUser(userId) {
        event.preventDefault();
        if (confirm("Are you sure you want to delete this user?")) {
            var row = $('#row_' + userId);

            $.ajax({
                url: '/Index/DeleteUser',
                type: 'POST',
                data: { userId: userId },
                success: function (result) {                  
                    location.reload();              
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText);
                }
            });
        }
    }

    function openUpdateModal(event, userId, userName, role,password) {
        event.preventDefault();
        $('#updateUserId').val(userId);
        $('#updateUserName').val(userName);
        $('#updateRole').val(role);
        $('#updatePassword').val(password);
        $('#updateModal').modal('show');
    }

    function updateRole() {
        var userId = $('#updateUserId').val();
        var userName = $('#updateUserName').val();
        var password = $('#updatePassword').val();
        var role = $('#updateRole').val();

        $.ajax({
            url: '/Index/UpdateRole',
            type: 'POST',
            data: { handler: 'UpdateRole', userId: userId, userName: userName, password: password, role: role },
            success: function (result) {
                location.reload(); 
            },
            error: function (xhr, status, error) {
                console.log(xhr.responseText);
            }
        });
    }

</script>